spring.application.name=cake-factory-back-end

#configuring spring to use the .env file
spring.config.import=optional:file:.env[.properties]

#Database connection using environmental variables instead of actual secrets
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


#Hibernate DDL auto config
spring.jpa.hibernate.ddl-auto=update

